services:
  monitorr:
    build: .
    container_name: monitorr
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/app/config.yml:rw
      - ./logs:/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
      - FLASK_SECRET_KEY=65485415687415
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: bridge
    labels:
      - "com.unraid.description=Monitorr - Docker Log Monitoring"
      - "com.unraid.icon=https://raw.githubusercontent.com/yourusername/Monitorr/main/icon.png"
      - "com.unraid.category=Monitoring" 